name: Github CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci && cp .env.example .env

      - name: Build
        run: npm run build

      - name: Lint files
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Deploy app
        uses: ./.github/actions/deploy/
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          user: ${{ vars.DEPLOY_USER }}
          server: ${{ vars.DEPLOY_SERVER }}
          deploy_path: ${{ vars.DEPLOY_PATH }}
